//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1_N1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G1_N1_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G1_N1_Class()
        {
            this.G1_N1_Attendance = new HashSet<G1_N1_Attendance>();
        }
    
        public int TeacherID { get; set; }
        public int GroupNumber { get; set; }
        public string SubjectCode { get; set; }
        public string RoomNo { get; set; }
        public string Day { get; set; }
        public string Description { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int Capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G1_N1_Attendance> G1_N1_Attendance { get; set; }
        public virtual G1_N1_Group G1_N1_Group { get; set; }
        public virtual G1_N1_room G1_N1_room { get; set; }
        public virtual G1_N1_subject G1_N1_subject { get; set; }
        public virtual G1_N1_Teacher G1_N1_Teacher { get; set; }
    }
}
