//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1_N1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADEntities : DbContext
    {
        public DADEntities()
            : base("name=DADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<G1_N1_Attendance> G1_N1_Attendance { get; set; }
        public virtual DbSet<G1_N1_Class> G1_N1_Class { get; set; }
        public virtual DbSet<G1_N1_Group> G1_N1_Group { get; set; }
        public virtual DbSet<G1_N1_room> G1_N1_room { get; set; }
        public virtual DbSet<G1_N1_Student> G1_N1_Student { get; set; }
        public virtual DbSet<G1_N1_subject> G1_N1_subject { get; set; }
        public virtual DbSet<G1_N1_Teacher> G1_N1_Teacher { get; set; }
    }
}
