//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Attendance
    {
        public System.DateTime SignIn { get; set; }
        public System.DateTime SignOut { get; set; }
        public int TeacherID { get; set; }
        public int GroupNumber { get; set; }
        public string SubjectCode { get; set; }
        public string RoomNo { get; set; }
        public int Barcode { get; set; }
        public Nullable<bool> EarlyLeave { get; set; }
        public Nullable<bool> Late { get; set; }

        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }

        public Attendance(DateTime signIn, DateTime signOut, int teacherID, int groupNumber, string subjectCode, string roomNo, int barcode, bool earlyLeave, bool late)
        {
            this.SignIn = signIn;
            this.SignOut = signOut;
            this.TeacherID = teacherID;
            this.GroupNumber = groupNumber;
            this.SubjectCode = subjectCode;
            this.RoomNo = roomNo;
            this.Barcode = barcode;
            this.EarlyLeave = earlyLeave;
            this.Late = late;
        }
}
   
}
