//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int TeacherID { get; set; }
        public int GroupNumber { get; set; }
        public string SubjectCode { get; set; }
        public string RoomNo { get; set; }
        public string Day { get; set; }
        public string Description { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int Capacity { get; set; }
    
        public virtual C_Group C_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual room room { get; set; }
        public virtual subject subject { get; set; }
        public virtual Teacher Teacher { get; set; }

        public Class(int teacherID, int groupNo, string subjectCode, string roomNo, string day, string description, System.TimeSpan starttime, System.TimeSpan endTime, int capacity)
        {
            this.TeacherID = teacherID;
            this.GroupNumber = groupNo;
            this.SubjectCode = SubjectCode;
            this.RoomNo = roomNo;
            this.Day = day;
            this.Description = description;
            this.StartTime = starttime;
            this.EndTime = endTime;
            this.Capacity = capacity;
        }
    }
}
