//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DADExampleEntities : DbContext
    {
        public DADExampleEntities()
            : base("name=DADExampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Group> C_Group { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<Table_Test> Table_Test { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Query1> Query1 { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int ADD_CUSTOMER(Nullable<int> pCUSTID, string pCUSTNAME)
        {
            var pCUSTIDParameter = pCUSTID.HasValue ?
                new ObjectParameter("PCUSTID", pCUSTID) :
                new ObjectParameter("PCUSTID", typeof(int));
    
            var pCUSTNAMEParameter = pCUSTNAME != null ?
                new ObjectParameter("PCUSTNAME", pCUSTNAME) :
                new ObjectParameter("PCUSTNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_CUSTOMER", pCUSTIDParameter, pCUSTNAMEParameter);
        }
    
        public virtual int ADD_EMPLOYEE(Nullable<int> staffID, string givenName, string surname)
        {
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(int));
    
            var givenNameParameter = givenName != null ?
                new ObjectParameter("GivenName", givenName) :
                new ObjectParameter("GivenName", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_EMPLOYEE", staffIDParameter, givenNameParameter, surnameParameter);
        }
    
        public virtual int DELETE_ALL_CUSTOMER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_ALL_CUSTOMER");
        }
    }
}
