//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query1
    {
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public string TourName { get; set; }
        public string Description { get; set; }
        public int EventYear { get; set; }
        public string EventMonth { get; set; }
        public int EventDay { get; set; }
        public Nullable<decimal> Payment { get; set; }
    }
}
